### ISSUE TITLE
Frictionless data in own section? 

### ISSUE THREAD

**Issue by mrjoh3** [karthik/ddd#106]
Hi, 

I've just been reading through your paper, really interesting and useful. 

One comment, in the [Python](https://github.com/karthik/ddd/blob/master/paper.md#python) paragraph you mention Open Knowledge Foundations frictionless data. As this has multiple language implimentations I think this could have its own paragraph or section with a little more explanation.

**Comment by njtierney** [comment]
Thanks for your kind comments, and for taking the time to read the paper! We have decided to not include this as it's own section, since it falls under the larger category of metadata. Thank you for your comment, it is much appreciated!
