### ISSUE TITLE
How can I cite it?

### ISSUE THREAD

**Issue by jromanowska** [karthik/ddd#110]
This paper is fantastic! I've been thinking about this for a while, and right now I am creating a presentation for my colleagues from the Institute about reproducible research principles - could I borrow some of the examples/figures from your paper? How should I cite it? If I give your names and the github repo address, it should be enough, right?

**Comment by njtierney** [comment]
Hi there @jromanowska !

So glad to hear that you like the paper, @karthik and I have been putting a lot of work into it.

We will be putting the paper up on arXiv in the coming week - you could cite that paper then, if you like? Or is your presentation sooner than that?

We'll have a think about the best way to cite the repo in its current state, we might put it on Zenodo to generate a DOI, should have an answer for you tomorrow.

**Comment by jromanowska** [comment]
The presentation is on 5th Feb., so I can wait till you've posted it on arXiv. Great, thanks!

**Comment by njtierney** [comment]
OK fantastic, we'll note here on this issue when it is up on arXiv

**Comment by njtierney** [comment]
Hi there @jromanowska - for the moment perhaps just link to the this repository in your talk, we are juuust about to submit it to arxiv - I'll post here when we do :)

**Comment by njtierney** [comment]
Hi @jromanowska - forgot to post that the paper is on arxiv now https://arxiv.org/abs/2002.11626
