### ISSUE TITLE
Installing packages maybe not so easy

### ISSUE THREAD

**Issue by cmaimone** [karthik/ddd#111]
Thanks for writing this and sharing early on.  A fairly minor issue: while the following is true especially in relation to how things were in the past (and in relation to working with data), installing packages is not always a trivial thing for many researchers.  Every week I get help requests from researchers just trying to get R or Python packages installed correctly.  And most don't know what a requirements file is.  A statement like this may alienate some of the audience you're trying to attract and encourage to share their data.

> In a modern computational workflow it is trivial for a user to `pip install` a package in Python, or use `install.packages` in R to install all software dependencies for a project. By relying on the idea of having research compendia [@gentleman2007statistical] or something as simple as a requirements file, one can easily install all the necessary scaffolding.

**Comment by njtierney** [comment]
Hi @cmaimone - thank you for your thoughtful comment. I agree with you - do you think something like this would address your comments? I've highlighted the new sections

> In a modern computational workflow **a user can `pip install`** a package in Python, or use `install.packages` in R to install all software dependencies for a project. By relying on the idea of having research compendia [@gentleman2007statistical] or something as simple as a requirements file, **it is relatively straightforward to** install all the necessary scaffolding.

**Comment by cmaimone** [comment]
Yes, that reads better.
